dist: trusty
sudo: false

language: node_js
node_js:
  - '10.15.3'

before_script:
  - npm install -g gulp-cli
  - npm install -g npm@6.12.0

script: gulp

cache:
  directories:
    - ./node_modules
    - ./bower_components
